apiVersion: batch/v1
kind: Job
metadata:
  name: test-hello
spec:
  backoffLimit: 5
  template:
    spec:
      containers:
      - name: demoapp
        image: astravinskyigl/demoapp:job
      restartPolicy: OnFailure
