name: Test Pull request creation

on:
  workflow_dispatch:
#   push:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

#     permissions:
#       id-token: write
#       contents: write

#     env:
#       DOCKER_USER: ${{ secrets.DOCKER_USER }}
#       DOCKER_HUB_REPO: demoapp
#       AWS_REGION: us-east-2
#       AWS_ROLE: arn:aws:iam::331226338131:role/ci-GithubActionsRole
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Fetch all commits
          fetch-depth: 0
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: astravinskyi-gl/ci-to-eks-test
          path: ci-to-eks-test
          
#       - name: Check status
#         run: |
#           TEST1=0.0.1
#           cd ci-to-eks-test
#           git checkout -b "update-mmg-version"
#           sed 's/# image:.*/# image: '"$TEST1"'/' CI-helper.py
#           git add CI-helper.py
#           git commit -m "feat: change mmg version"
#           git push origin update-mmg-version

      - name: Edit file
        run: |
          TEST1=0.0.1
          cd ci-to-eks-test
          git config user.name "CI Actions Bot"
          git config user.email "<>"
          git checkout -b "update-mmg-version"
          sed 's/# def print_hi(name):/# image: '"$TEST1"'/' CI-helper.py
          git add CI-helper.py
          git commit -m "feat: change mmg version"
          gh pr create --title "feat: update mmg version" --reviewer astravinskyi-gl
          
#       - name: Create pr
#         uses: peter-evans/create-pull-request@v4
#         with:
#           path: ci-to-eks-test
#           add-paths: ci-to-eks-test/*
#           token: ${{ secrets.PAT }}
#           commit-message: 'feat: update mmg version'
# #           committer: ci-workflow
# #           author: ci-workflow
#           branch: update-mmg-version
#           delete-branch: true
#           reviewers: astravinskyi-gl
         
      - name: Check status
        run: |
          git status
          git branch
